// AUTO-GENERATED by `astroassist eval fixtures --ts`. Do not edit by hand.
// Regenerate after changing artifact models so UI and backend stay in sync.

export const echoValue = {
  "id": "art_01M331VJ0C51XXBABRH3JWJBVV",
  "kind": "ScientificValue",
  "summary": "Echo complete \u2014 5 characters echoed",
  "provenance": {
    "artifact_id": "art_01M331VJ0C51XXBABRH3JWJBVT",
    "created_at": "2026-09-21T22:37:15.660642Z",
    "method": "derived",
    "source": "astroassist",
    "source_version": null,
    "source_record_id": null,
    "query_id": null,
    "inputs": [],
    "tool": "echo@1",
    "code_hash": null,
    "parameters": {},
    "citation_keys": [],
    "quality_flags": {},
    "warnings": []
  },
  "parent_id": null,
  "value": {
    "value": 5.0,
    "unit": ""
  },
  "uncertainty": null,
  "distribution": null,
  "limits": null
};

export const scientificValue = {
  "id": "art_01M331VJ0C51XXBABRH3JWJBVX",
  "kind": "ScientificValue",
  "summary": "distance = 4.965 \u00b1 0.010 pc",
  "provenance": {
    "artifact_id": "art_01M331VJ0C51XXBABRH3JWJBVW",
    "created_at": "2026-09-21T22:37:15.660689Z",
    "method": "derived",
    "source": "Gaia DR3",
    "source_version": null,
    "source_record_id": null,
    "query_id": null,
    "inputs": [],
    "tool": null,
    "code_hash": null,
    "parameters": {},
    "citation_keys": [],
    "quality_flags": {},
    "warnings": []
  },
  "parent_id": null,
  "value": {
    "value": 4.965,
    "unit": "pc"
  },
  "uncertainty": {
    "symmetric": {
      "value": 0.01,
      "unit": "pc"
    },
    "lower": null,
    "upper": null
  },
  "distribution": null,
  "limits": null
};

export const resolvedObject = {
  "id": "art_01M331VJ0DYZK7M9PQ6088RT7T",
  "kind": "ResolvedObject",
  "summary": "AD Leo (M3.5Ve flare star)",
  "provenance": {
    "artifact_id": "art_01M331VJ0C51XXBABRH3JWJBVY",
    "created_at": "2026-09-21T22:37:15.660766Z",
    "method": "resolver",
    "source": "SIMBAD",
    "source_version": null,
    "source_record_id": null,
    "query_id": null,
    "inputs": [],
    "tool": null,
    "code_hash": null,
    "parameters": {},
    "citation_keys": [],
    "quality_flags": {},
    "warnings": []
  },
  "parent_id": null,
  "canonical_name": "AD Leo",
  "aliases": [
    "GJ 388",
    "V* AD Leo"
  ],
  "coordinate": {
    "ra_deg": 154.9017,
    "dec_deg": 19.8699,
    "frame": "icrs",
    "epoch": null
  },
  "object_type": "Flare Star",
  "spectral_type": "M3.5Ve",
  "resolver": "SIMBAD",
  "resolver_id": null
};

export const query = {
  "id": "art_01M331VJ0DYZK7M9PQ6088RT7W",
  "kind": "QueryArtifact",
  "summary": "SIMBAD resolve 'AD Leo'",
  "provenance": {
    "artifact_id": "art_01M331VJ0DYZK7M9PQ6088RT7V",
    "created_at": "2026-09-21T22:37:15.661208Z",
    "method": "resolver",
    "source": "SIMBAD",
    "source_version": null,
    "source_record_id": null,
    "query_id": null,
    "inputs": [],
    "tool": null,
    "code_hash": null,
    "parameters": {},
    "citation_keys": [],
    "quality_flags": {},
    "warnings": []
  },
  "parent_id": null,
  "source": "SIMBAD",
  "protocol": "astroquery",
  "query_text": "Simbad.query_object('AD Leo')",
  "status": "ok",
  "started_at": null,
  "finished_at": null,
  "runtime_ms": 243,
  "row_count": 1,
  "bytes": null,
  "raw_response_path": null,
  "error": null,
  "retries": 0
};

export const artifactFixtures = { echoValue, scientificValue, resolvedObject, query };
